apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webcolor
  namespace: webcolor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /webpage
          pathType: Prefix
          backend:
            service:
              name: webpage
              port:
                number: 80  
        - path: /webpage/(.*)  # Note a barra extra
          pathType: Prefix
          backend:
            service:
              name: webpage
              port:
                number: 80