apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webcolor
  namespace: webcolor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: webpage.pablomesquita.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: webpage
              port:
                number: 80  